### ISSUE TITLE
FM Radio not working

### ISSUE THREAD

**Issue by serverwentdown** [varunchitre15/android_device_sony_taoshan#1]
FM Radio can scan and show channel information (station title) but no audio. Is this a bug in CM12 or in the deice drivers?

**Comment by abielzulio** [comment]
Maybe you can provide a logcat? So it would be easier to identify it is CM12 bug or device-specific bug @ambrosechua

**Comment by serverwentdown** [comment]
https://gist.github.com/ambrosechua/afe5ecc697858ca01b40
